{% set name = "qpbo" %}
{% set version = "0.3.11" %}
{% set sha256 = "d4c60d6b5da4d2eabee254fd4989129f01e6fd077fb3dfc5cf01e9e6ede5fb74" %}
#"bdf64d3bb31fd00c74182dbc0b477892eb8b7d550d19b46f0561b8789c7c48b8" %}
#"b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #path: ../
  #fn: qpbo-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/qpbo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/qpbo  # [unix]
    - test -f ${PREFIX}/include/qpbo/QPBO.h  # [unix]
    - test -f ${PREFIX}/include/qpbo/block.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\qpbo\QPBO.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\qpbo\block.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/qpbo
  license: GPL
  license_family: GPL
  license_file: LICENCE
  summary: 'QPBO'
  description: 'QPBO'
  documentation_url:  https://github.com/DerThorsten/qpbo
  dev_url: https://github.com/DerThorsten/qpbo

extra:
  recipe-maintainers:
    - Sebastianborszcz
