{% set name = "libdai" %}
{% set version = "0.4.1" %}
{% set sha256 = "da22b29b12646bc8c31e02bd90d2dfe2c2299cae334bf4576b0e7e5dcfedad7c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #path: ../
  #fn: libdai-{{ version }}.tar.gz
  url: https://github.com/Sebastianborszcz/ad3
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - boost-cpp >=1.4
    - gmp
  run:
    - gmp

test:
  commands:
    - test -d ${PREFIX}/include/dai  # [unix]
    - test -f ${PREFIX}/include/dai/alldai.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\dai\alldai.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/libdai
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'libDAI'
  description: 'libDAI'
  doc_url:  https://github.com/DerThorsten/libdai
  dev_url: https://github.com/DerThorsten/libdai

extra:
  recipe-maintainers:
    - Sebastianborszcz
