{% set name = "libdai" %}
{% set version = "0.4.1" %}
{% set sha256 = "8c4b4c55512ae27a2ab1d2d0e88f634e143a46f5519b08b7b155974c16410eea" %}
#"dde6a54483c1ecfbea53280d405abd3ebbd54dad146a26df08fcc9ac9ae23031" %}
#"06615f72717a537697281e210c559b9491737852438952d26767b85a2f313d26" %}
#"7c4bdf7791039deaf74e2841e2d38bd7a13a0437a6d262c35236c1319e813518" %}
#"b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #path: ../
  #fn: libdai-{{ version }}.tar.gz
  url: https://github.com/Sebastianborszcz/ad3
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - boost-cpp >=1.4
    - gmp
  run:
    - gmp

test:
  commands:
    - test -d ${PREFIX}/include/dai  # [unix]
    - test -f ${PREFIX}/include/dai/alldai.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\dai\alldai.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/libdai
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'libDAI'
  description: 'libDAI'
  documentation_url:  https://github.com/DerThorsten/libdai
  dev_url: https://github.com/DerThorsten/libdai

extra:
  recipe-maintainers:
    - Sebastianborszcz
